# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-18 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbfg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesentence',
            name='link_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
