# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-19 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mainbfg', '0002_typesentence_link_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelManagers(
            name='categories',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='typesentence',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
