# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-20 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbfg', '0003_auto_20170419_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='icon_style',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='categories',
            name='is_icon_img',
            field=models.BooleanField(default=False),
        ),
    ]
