# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-08 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbfg', '0005_payment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='payment',
        ),
    ]
