# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-14 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbfg', '0009_auto_20170513_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_id',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
