# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-17 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbfg', '0010_auto_20170514_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typesentence',
            name='name',
        ),
    ]
