# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-17 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbfg', '0011_remove_typesentence_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesentence',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
