# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-20 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbfg', '0012_typesentence_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
