# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-22 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbfg', '0014_auto_20170522_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='end_time_paid',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='start_time_paid',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='type_img_s',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
