# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-26 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import mainbfg.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbfg', '0015_auto_20170522_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='dirname_img',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='autor',
            field=models.CharField(error_messages={'max_length': 'Required error'}, max_length=30),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='caption',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='full_adress',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='main_img',
            field=models.ImageField(blank=True, upload_to=mainbfg.models.custom_directory_path),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='meta_info',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
